### ISSUE TITLE
Separate Airlines, Aircraft and spawning from the Airport

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#135]
_From @n8rzz on December 23, 2016 23:17_

see: http://codepen.io/n8rzz/pen/eBobXm?editors=0010 and http://codepen.io/erikquinn/pen/VmOKqp?editors=0012

_Copied from original issue: n8rzz/atc#243_

**Comment by erikquinn** [comment]
_From @n8rzz on December 26, 2016 15:44_

#### create the following:
- [x] single `aircraft` json file that is a combination of all individual aircraft definitions
- [x] single `airline` json file that is a combination of all individual airline definitions
- [x] `AircraftCollection`
- [x] tests `AircraftCollection`
- [x] `AircraftDefinition`
- [x] tests `AircraftDefinition`
- [x] `AirlineCollection`
- [x] tests `AirlineCollection`
- [x] simplified `AirlineModel`
- [x] tests simplified `AirlineModel`
- [x] `navigationLibrary/FixCollection` (non-static version of current `FixCollection`)
- [x] tests `navigationLibrary/FixCollection` (non-static version of current `FixCollection`)
- [x] `navigationLibrary/FixModel`
- [x] tests `navigationLibrary/FixModel`
- [x] `trafficGenerator/SpawnPatternCollection`
- [x] tests `trafficGenerator/SpawnPatternCollection`
- [x] `trafficGenerator/SpawnPatternModel`
- [x] tests `trafficGenerator/SpawnPatternModel`
- [x] `trafficGenerator/SpawnScheduler`
- [x] tests `trafficGenerator/SpawnScheduler`

#### TODO:
- [x] create `addItems()` and `addItem()` methods for `SpawnPatternCollection`
- [x] move initial delay calculation to `SpawnPatternModel`
- [x] handle updated `spawnPattern` object from airport json
- [x] create `navigationLibrary` (controller?) and add facades to access `FixCollection` and `StandardRoute`
- [x] move `StandardRoute` to `navigationLibrary`
- [x] Calculate position and heading for arriving aircraft (1 [x]  2[x])
- [x] integrate new `AircraftCollection` and `SpawnScheduler` into app
- [x] move position and heading calculation from `AircraftCollection` to `SpawnPatternModel`
- [x] handle arrival altitude ranges
- [x] determine `destination` for arrivals
- [x] initial departure speed `NaN` 
- [x] improve delay calculations
- [x] provide way for `SpawnScheduler` to handle app pause
- [x] provide way for `SpawnScheduler` to handle loss of focus
- [x] provide way for `SpawnScheduler` to handle timewarp
- [x] provide way to reset applicable classes on airport change (`AirlineCollection` and `AircraftCollection.definitionList` should never change on airport change)
- [x]  handle specific airline fleets
- [x] handle callsign logics within `AirlineModel`
- [x] add `SpawnPatternModel` to pool
- [x] move `aircraftController` and `airlineController` out of `airportController` and use the controllers to fire off the collection methods
- [x] move aircraft creation back to `aircraftController`
- [x] update `airline_get` to use `airlineCollection`
- [x] Handle other spawn types (cyclic, wave, surge)
- [x] handle initial spawn onLoad
- [x] pass `navigationLibrary` to `canvasController` and update `.canvas_draw_sids()`
- [x] make `flightNumbers` globally unique.  `UAL123` and `AAL123` should not be possible
- [x] deprecate current `aircraft.callsign` properties
- [x] clear old schedules from timeouts queue on airport change (`game_clear_timeout`)
- [x] add readme for `spawnPatterns`
- [x] pass `navigationLibrary` to `AircraftInstanceModel` an `AircraftFlightManagementSystem`
- [x] move `StandardRoute` refs in airport to `NavigationLibrary`
- [x] move `RouteModel` to `navigationLibrary`
- [x] handle simple and complex RouteStrings, ex: `YOSEM.YOSEM3.KSFO` vs `TULNI..AKOVI..EBBR` (see: `AircraftFlightManagementSystem.formatRoute`)
- [x] handle departure preSpawns
- [x] remove deprecated properties, methods and files
    - [x] `AircraftModel`
    - [x] `arrivals/`
    - [x] `departures/`
    - [x] `AirlineModelComplex`
- [x] address `b764` aircraft issue
- [x] fleet is undefined when instance model is instantiated 
- [x] loading an airport without terrain fails
- [x] update/move view logic in `AirportModel.set()`
- [x] loading spinner and text under aircraft strips do not get removed when loading kbos
- [x] copy spawnMethod doc blocs with diagrams
- [x] add `validateSpawnPatternData` helper function that halts instantiation
- [ ] add changelog entry
- [ ] allow `entrail` property
- [ ] wave pattern not working
- [ ] update airport files with `spawnPatterns` (need help on below)
    - [ ] kjfk
    - [ ] kmsp
    - [ ] ksan
    - [ ] itba
    - [ ] omaa
 

#### NICE TO HAVE
these will become standalone issues if they cannot be finished
- [ ] ~add `AppView` class~ ( n8rzz/atc#259 )
- [ ] create `SpawnPatternPeriodCalculator` class to handle delay calculations

**Comment by n8rzz** [comment]
finished here: https://github.com/n8rzz/atc/issues/243
