### ISSUE TITLE
Refactor FMS

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#139]
#### story goals:
- accept a `routeString` or a collection of `FixModels` on instantiation
- add helper functions that can build `Leg`s and `Waypoint`s from a routeString
- make heading, speed altitude class properties _informed_ by fix restrictions
- consolidate `StandardRouteWaypointModel`, `Waypoint` and `FixModel`
    - this will likely necessitate a builder method within `FixModel` that can build a `Waypoint`
    - `StandardRouteWaypointModel` seems duplicative of `Waypoint`
- add method to `FixCollection` to generate new pooled `PositionModel` from coordinates that uses stored reference position

---
## ISSUES
- [ ] rr a plane repeatedly they will eventually just stop rr and just fly straight. but will say `rerouting to :XYZ`

## ADDITIONAL SPECS
Must also fulfill specifications from all of the below:
- [x] openscope/openscope#158 
- [x] openscope/openscope#129 
- [x] openscope/openscope#165 
- [x] openscope/openscope#114 
- [x] openscope/openscope#73 
- [x] openscope/openscope#87 
- [x] openscope/openscope#197 
- [x] openscope/openscope#277 
- [x] openscope/openscope#20 
- [x] openscope/openscope#153 
- [x] openscope/openscope#122

## DONE
- [x] parallel arrivals to 7r and 8 gives conflict notification even when both are established on localizer prior to descending on the glideslope
- [x] altitude readback and strip differ near lowest altitude (ex: at EDDM, assign `c 10`)
- [x] leader lines only show when aircraft is selected, and always point straight north
- [ ] ~~Add readbacks from aircraft that are asked to exceed their performance limitations (climb above ceiling, slow below `model.speed.min`, speed up above `model.speed.max`)~~
    - added [326](https://github.com/openscope/openscope/issues/326)
- [x] `rr FIX land` results in an undefined `destinationText` value
    - `AircraftStripView.updateViewForCruise()` has a switch on waypoint navmode, which is wrongfully assuming all aircraft in `CRUISE` mode are on `LNAV`. This needs to be reexamined, because rerouting and then clearing for approach throws here.
- [x] Airports with runways with elevations fail to load (ex: OTHH)
- [x] Video maps are not being drawn
- [x] You can taxi airborne aircraft to the runway
- [x] `[false, 'roger, reading back instructions']` boolean not causing red colored response when false
- [x] strips using `AircraftInstanceModel.mode` instead of `AircraftInstanceModel.flightPhase`
- [x] Remove use of `AircraftInstanceModel.mode`
- [x] using `turn right` or any direct command does not work
- [x] pre-spawn aircraft spawn at an altitude that is too high and don't descend to airspace ceiling until halfway through the airspace
- [x] `hold` command fails when not passed fixName
- [x] aircraft info box shows speed at `00`
- [x] `kbos` appears in airport list but does not load
- [x] update milestone names
- [x] update sprint names
- [x] `Fms.flightPlanRoute` is not updated when `sid` command is used to change the departure procedure
- [x] `Fms.nextWaypoint()` does not return early when switching to the next leg
- [ ] ~~one arrival via the EAGUL6 (out of 3 so far) decided to do a 540 degree turn over HINEY~~ **(cannot reproduce)**
- [x] arrivals touchdown, don't slow down and keep going off the end of the runway forever
- [x] Told aircraft to hold at TEICH. Then after 2 turns DCT TESLE. Aircraft departed the hold on a 180 heading. And then no longer listens to commands.
- [x] add changelog entries and update related tickets
- [x] remove any references to `__fms__` or `AircraftFlightManagementSystem` in `AircraftInstanceModel`
- [x] remove `AircraftFlightManagementSystem.js` and tests (if any)
    - [x] remove `Leg.js` and tests (if any)
    - [x] remove `Waypoint.js` and tests
- [x] after two aircraft move outside conflict window, they both remain red
- [x] departures spawn at airport center
- [x] departures do not have a takeoff run, they immediately gain altitude and start moving from aircraft center
- [x] departures have the wrong heading, they do not follow the runway angle correctly
- [x] departures turn immediately after start takeoff roll. they should wait till min height until they turn on course
- [x] departures do not gain altitude after they reach v1
- [x] aircraft do not honor speed restriction when under 10k
- [x] aircraft strip never changes from takeoff for departures
- [x] aircraft strip never changes to holding for hold
- [x] `runFix is not a function` I believe this was removed. 
    - [x] we need to update docs
    - [x] remove references from the `CommandParser`
- [x] departing aircraft are never removed and simply fly out of view
- [x] after prespawn at `ksfo`, only `QUINN.BDEGA2.KSF` continues to spawn arrivals
- [x] `taxi 28l` returns the correct responses, but does not show the aircraft info box or properly update the runway assignments in the Aircraft.
- [x] `sid PROCEDURE` does not update strip destination until `caf` is issued
- [x] arrivals on ils do not show separation indicator
- [x] arrivals capturing localizer look to be locked but don't gain capture until established for a while
- [x] arrivals perform a touch and go
    - aircraft descend to ground but then don't slow down and instead gain altitude and fly a missed approach
- [x] arrival shows dotted line from last star fix all the way down approach path
- [x] departing aircraft show the separation indicator

**Comment by erikquinn** [comment]
Separate the MCP from the FMS. The FMS should be rarely altered; only really during reroutes (such as SID/STAR/TRXN/IAP assignments), and this means that when we tell an airplane to fly a particular heading, that *does not qualify as a reroute*, and yet that is how it is treated currently, as everything is done with waypoints. This also creates a much tighter parallel with reality, and allows for us to do common things such as enabling LNAV, VNAV, and speed all independently, and in a way that airplane people could make sense of, because that is how it works in real aircraft.

More on this later.

**Comment by n8rzz** [comment]
## TODO
- [ ] aircraft spawn successfully with a procedureRoute string
- [ ] aircraft spawn successfully with a directRoute string
- [ ] aircraft spawn successfully with a complexRoute string

## ISSUES
- [ ] aircraftController uses currentWaypoint.navmode when determining if an aircraft should be removed
