### ISSUE TITLE
Add "labelPositions" to restricted areas

### ISSUE THREAD

**Issue by OlaRune** [openscope/openscope#1721]
**Background**
When defining airspaces in airport files it is possible to place one or more labels at custom locations for each airspace, using the attribute "labelPositions", which is useful for airspaces with strange geometry. (This functionality is not documented yet, see issue _Missing documentation of "labelPositions" in airport files_ #1711")

**Suggestions**
This functionality is not implemented for restricted areas, but it should be pretty straight forward to implement it in the same way as for airspaces.

**Tasks**
- [x] Implement functionality for specifying labelPositions for restricted areas
- [x] Document new functionality in documentation/airport-format.md
- [x] Also document functionality for "labelPositions" when defining airspaces in this issue instead of #1711
