### ISSUE TITLE
Change syntax for restricted area definition to the same as airspace definition

### ISSUE THREAD

**Issue by OlaRune** [openscope/openscope#1722]
**Background**
When defining airspaces and restricted areas in airport files a polygon is defined for each. When defining airspaces this is done via the "poly" attribute, and when defining restricted areas it is done via the "coordinates" attribute.

**Suggestions**
Change the "coordinates" attribute in restricted area definitions to "poly", they both define the same thing in principle and it is more clear if they have the same syntax.

**Tasks**
- [x] Change the syntax in restricted area definition from "coordinates" to "poly"
- [ ] ~~Make sure to update any tests if needed~~ (the tests still work)
- [x] Update documentation/airport-format.md
- [x] Update all airport files in assets/airports to the new syntax

**Comment by OlaRune** [comment]
Maybe even make them use the exact same methods for polygon construction? Then enhancements only have to be

**Comment by OlaRune** [comment]
I just had a shower thought (without showering), but I know nothing about javascript so bear with me. Please tell me what you think of this.

Maybe geometric/geographic parameters can be generalized into a lib or toolset where they can be used in different contexts with the same syntax and functionality.

For example:
- Polygons (defined by their vertices (latlon)
- Circles (defined by their center (latlon) and their radius (in either nm, mile or km)
- Lines defined by their endpoints (latlon)
- Lines defined as a starting point (latlon), bearing (deg) and distance (in either nm, mile or km)

These geometric objects can then be used in one, multiple or all of these contexts:
- Airspace definitions
- Restricted area definitions
- Radar video map definitions

Thoughts @erikquinn @Fechulo @cake-pie others? :)

**Comment by erikquinn** [comment]
That would likely be a much larger project even than it appears at face value. Down to the magical point in poly math etc would have to change from it's relatively simple one to a more complex implementation that supports arcs/circles. It could be doable with a third party library somehow (like Turf.js has an [intersect](https://turfjs.org/docs/#intersect) function for this, etc). I'd argue that the astronomic cost is not worth the benefit of saving airport developers the effort of converting arcs/circles to simple polylines.

Separately, a simple class to validate and handle input coordinates wouldn't hurt, though I will say that the majority of what you outlined would be stuff that belongs as methods of the PositionModel. In an ideal world, the position models themselves would be passed to the using class (say, the CanvasController), who could get the data in the form that they need it by calling methods of the position model. We've made some changes to that effect recently, but there's still a lot of manual, hard to track maths being done inline in places that are hard to track, cause bugs, and should be more centralized.

So personally, I'd make the format of the restricted areas and airspace and such the same, and call it a day from there. There's very little between that small change and tearing out everything (which I do not want to do).

**Comment by Fechulo** [comment]
> I'd argue that the astronomic cost is not worth the benefit of saving airport developers the effort of converting arcs/circles to simple polylines.

I agree. It'd be cool form an airport development perspective, but almost definitely not worth the effort.

**Comment by OlaRune** [comment]
> > I'd argue that the astronomic cost is not worth the benefit of saving airport developers the effort of converting arcs/circles to simple polylines.
> 
> I agree. It'd be cool form an airport development perspective, but almost definitely not worth the effort.

All right, I understand where both of you stand and I agree that it's not worth investing many many hours to add a small convenience. I'll carry on my crusade against inconsistent syntax by writing simple renaming issues instead of aiming for deeper harmonization/generalization.

**Comment by erikquinn** [comment]
That'll do! Thanks 😃
