### ISSUE TITLE
Add pronunciation to fixes in airport files

### ISSUE THREAD

**Issue by OlaRune** [openscope/openscope#1732]
# Background
In real life there are fixes whose identifiers resemble real words, in these cases they are often pronounced as these words by pilots and ATC. There can also be fixes named after places on the ground, whose identifier is an abbreviation of that. In those cases they are often pronounced as the place name.

An example is [this Youtube video](https://youtu.be/EWAsQ3qldo8) where the aircraft in their mayday call reports that their intention is to continue direct to SPRKY, which they pronounce "Sparky".

# Suggestion
Add an **optional** `spoken` parameter that can be used when defining fixes, which tells the sim how the identifier is pronounced, similar to how `name` works for SIDs and STARs.

This can also be used for forcing some readouts to use the phonetic alphabet if the voice engine tries to be too clever for its own good, and things just get weird, as commented by @cake-pie below.

# Subtasks
- [x] Add an optional parameter `spoken` to fix definitions
- [x] Make the text-to-speech use the `spoken` parameter if it exists
- [x] Update documentation/airport-format.md
- [x] Update tests accordingly

**Comment by cake-pie** [comment]
+1, this was also on my list of unfiled todo issues.

Suggest calling it `pronounce` or `reading` property rather than `name`, for a more meaningful property name.

Furthermore this can also apply to fixes that are not intended to be read naturally as a word.
At EDDM it can get quite absurd how different voices interpret & render waypoints DM4XX differently, because the voice engine tries to be too clever for its own good:

e.g.
- "Daniel" reads "dee em four hundred and twenty seven"
- "Alex" reads "four hundred twenty seven deutsche marks"
- "Google UK English Male" reads "four hundred twenty seven German marks"

Whereas in reality it is quicker and clearer to read numbers as "four two seven".

Oh, and `9` should be spelled `niner` for maximum authenticity.

**Comment by OlaRune** [comment]
> +1, this was also on my list of unfiled todo issues.
> 
> Suggest calling it `pronounce` or `reading` property rather than `name`, for a more meaningful property name.
> 
> Furthermore this can also apply to fixes that are not intended to be read naturally as a word.
> At EDDM it can get quite absurd how different voices interpret & render waypoints DM4XX differently, because the voice engine tries to be too clever for its own good:
> 
> e.g.
> 
>     * "Daniel" reads "dee em four hundred and twenty seven"
> 
>     * "Alex" reads "four hundred twenty seven deutsche marks"
> 
>     * "Google UK English Male" reads "four hundred twenty seven German marks"
> 
> 
> Whereas in reality it is quicker and clearer to read numbers as "four two seven".
> 
> Oh, and `9` should be spelled `niner` for maximum authenticity.

Thanks! I changed the issue text above. What do you think of "readout" for the parameter name?

**Comment by cake-pie** [comment]
`readout` works too!

**Comment by erikquinn** [comment]
Readout sounds like a printed string to me. How about like `spoken` / `spokenAs`? Could do `pronunciation` but it's long _and_ has a tendency to be misspelled.

**Comment by OlaRune** [comment]
> Readout sounds like a printed string to me. How about like `spoken` / `spokenAs`? Could do `pronunciation` but it's long _and_ has a tendency to be misspelled.

Yes, I agree! I like `spoken` better than any of the other proposals this far. I'll change the text above and the other similar issue I made.

**Comment by Hawaiicoder** [comment]
Should I add this feature to BWI or is this too far in the future? Happy to add it in the future if that’s the case.

**Comment by OlaRune** [comment]
> # Background
> In real life there are fixes whose identifiers resemble real words, in these cases they are often pronounced as these words by pilots and ATC. There can also be fixes named after places on the ground, whose identifier is an abbreviation of that. In those cases they are often pronounced as the place name.
> 
> An example is [this Youtube video](https://youtu.be/EWAsQ3qldo8) where the aircraft in their mayday call reports that their intention is to continue direct to SPRKY, which they pronounce "Sparky".
> 
> # Suggestion
> Add an **optional** `spoken` parameter that can be used when defining fixes, which tells the sim how the identifier is pronounced, similar to how `name` works for SIDs and STARs.
> 
> This can also be used for forcing some readouts to use the phonetic alphabet if the voice engine tries to be too clever for its own good, and things just get weird, as commented by @cake-pie below.
> 
> # Subtasks
> * [ ]  Add an optional parameter `spoken` to fix definitions
> * [ ]  Make the text-to-speech use the `spoken` parameter if it exists
> * [ ]  Update documentation/airport-format.md

**Comment by OlaRune** [comment]
> Should I add this feature to BWI or is this too far in the future? Happy to add it in the future if that’s the case.

I don't see any reason why this can't be done now. By the way I had forgotten to change the parameter name to `spoken` in the description, but I changed it now.
