### ISSUE TITLE
Change "name" parameter in SID and STAR definitions to something more fitting

### ISSUE THREAD

**Issue by OlaRune** [openscope/openscope#1735]
# Background
When defining SIDs and STARs in airport files the `name` parameter is supplied in order to tell the voice engine how to pronounce the ICAO identifier for the procedure.

As discussed in issue #1732, `readout` is a better parameter name.

# Suggestion
Change the parameter `name` in SID and STAR definitions to `readout`, with unchanged functionality.

# Subtasks
- [ ] Change `name` to `readout` in SID definitions
- [ ] Change `name` to `readout` in STAR definitions
- [ ] Update all files in assets/airports to the new syntax
- [ ] Update documentation/airport-format.md
