### ISSUE TITLE
Leg length for hold definitions in airport files only allows integer minutes

### ISSUE THREAD

**Issue by OlaRune** [openscope/openscope#1741]
# Background
**Example:** When defining a holding pattern at a waypoint with an initial heading of 090, left turns, 1 minute legs and a speed restriction of 230 knots the following string is used: `"090|left|1min|S230-"`.

When trying to implement the Stockholm/Arlanda airport (#1695), 1.5 minute legs are used for some holds. When using this it gives a runtime error `Uncaught Error: Unexpected parameter for Fix 'ELTOK': 1.5min`.

After looking at the code I found that the following regular expression in `globalConstants.js` is responsible for validating if the argument is a leg length: `HOLD_DISTANCE: /^([1-9]|1[0-9])(nm|min)$/i,`

It obviously only allows integer leg lengths between 1 and 19 nautical miles or minutes, not fractions.

## Suggestion
Edit the regular expression to allow leg lengths with one decimal between 0.1 and 19.9 min or nm. It should still be valid to use integers between 1 and 19 as before.

## Subtasks
- [x] Edit the regular expression to allow decimals as stated above
- [x] Do  code inspection to make sure decimal leg lengths shouldn't break anything
- [x] Do some manual testing to see that it works as intended
- [x] If issue #1737 is still open, mention this new information there
- [ ] <s>If issue #1737 is closed, update the documentation that the issue added to airport-format.md</s>
